workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      sdk: 30
    scripts:
      - name: Build Android APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
