workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
